### ISSUE TITLE
ngx-annotation-text@16.0.0 not compatible with the angular/common@17.2.3

### ISSUE THREAD

**Issue by KhoaLee** [philenius/ngx-annotate-text#19]
Do you guys have plan to upgrade this repo to suitable for angular 17? 
<img width="613" alt="image" src="https://github.com/philenius/ngx-annotate-text/assets/33981342/0af961a0-f7b3-4d8a-b5b6-f0e30c3963ad">

**Comment by miccou** [comment]
I'm happy to have a go

**Comment by philenius** [comment]
@KhoaLee and @miccou , thank you for the reminder. I just released v17.2.0 of this package with #22  :rocket:
