### ISSUE TITLE
[Bug] Replace BrowserModule Import with CommonModule in ngx-annotate-text.module.ts

### ISSUE THREAD

**Issue by elucidata-rohit** [philenius/ngx-annotate-text#2]
This is resulting in `BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.` Error. As we're using this module in a Lazy loaded module.

Let me know if I can raise a PR to fix this.

**Comment by philenius** [comment]
Thanks for reporting this issue. Your PR is very welcome :) 

Btw, which Angular version are you using? I have seen that someone forked my library and bumped it to Angular v12. In April, I plan to change the versioning of my library to match the versioning of Angular itself. So, there'll be `12.0.0` and `13.0.0` versions of `ngx-annotate-text`.

**Comment by philenius** [comment]
@elucidata-rohit: duplicate import of BrowserModule is fixed with version 0.1.4 and all following versions
